apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k31f1m4ed-go
  janus-idp.io/tekton: k31f1m4ed-go
  backstage.io/kubernetes-id: k31f1m4ed-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k31f1m4ed-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
